#!/usr/bin/env bash
#
# generate-schema-doc.sh — snapshot the current public schema into docs/SCHEMA.md.
#
# Usage:  ./scripts/generate-schema-doc.sh          (from repo root)
#         npm run schema-doc                         (from scripts/)
#
# Requires: psql, SUPABASE_DB_URL (env var or in .env at repo root).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/docs/SCHEMA.md"

# Prefer env var (CI sets it directly); fall back to .env for local dev.
if [ -z "${SUPABASE_DB_URL:-}" ] && [ -f "$REPO_ROOT/.env" ]; then
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.env"
fi

if [ -z "${SUPABASE_DB_URL:-}" ]; then
  echo "Error: SUPABASE_DB_URL is not set. Provide it as an env var or in .env." >&2
  exit 1
fi

run_psql() {
  psql "$SUPABASE_DB_URL" -tAX "$@"
}

GENERATED_AT="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

# Collect views first (before entering the group command)
VIEW_NAMES="$(run_psql -c "
SELECT viewname
FROM pg_views
WHERE schemaname = 'public'
ORDER BY viewname;
")"

# Build doc in a subshell group, redirect once
{
cat <<HEADER
# CoasterRank — Production Schema

> Auto-generated by \`scripts/generate-schema-doc.sh\`.
> Generated: ${GENERATED_AT}
>
> **To regenerate:** \`cd scripts && npm run schema-doc\`

---

## Enums

| Enum | Values |
|------|--------|
HEADER

run_psql -c "
SELECT t.typname,
       string_agg(e.enumlabel, ', ' ORDER BY e.enumsortorder)
FROM pg_type t
JOIN pg_enum e ON t.oid = e.enumtypid
JOIN pg_namespace n ON t.typnamespace = n.oid
WHERE n.nspname = 'public'
GROUP BY t.typname
ORDER BY t.typname;
" | while IFS='|' read -r name values; do
  echo "| \`$name\` | $values |"
done

echo ""
echo "---"
echo ""
echo "## Tables"
echo ""

run_psql -c "
SELECT table_name, column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_schema = 'public'
ORDER BY table_name, ordinal_position;
" | awk -F'|' '
BEGIN { prev="" }
{
  gsub(/^ +| +$/, "", $1)
  gsub(/^ +| +$/, "", $2)
  gsub(/^ +| +$/, "", $3)
  gsub(/^ +| +$/, "", $4)
  table=$1; col=$2; dtype=$3; nullable=$4
}
table != prev {
  if (prev != "") printf "\n"
  printf "### `%s`\n\n", table
  printf "| Column | Type | Nullable | Notes |\n"
  printf "|--------|------|----------|-------|\n"
  prev=table
}
{ printf "| `%s` | %s | %s | |\n", col, dtype, nullable }
'

echo ""
echo "---"
echo ""
echo "## Constraints"
echo ""
echo "| Table | Column | Constraint | References |"
echo "|-------|--------|------------|------------|"
run_psql -c "
SELECT tc.table_name,
       string_agg(kcu.column_name, ', ' ORDER BY kcu.ordinal_position) AS columns,
       tc.constraint_type,
       CASE WHEN tc.constraint_type = 'FOREIGN KEY'
            THEN (SELECT ccu.table_name
                  FROM information_schema.constraint_column_usage ccu
                  WHERE ccu.constraint_name = tc.constraint_name
                    AND ccu.table_schema = tc.table_schema LIMIT 1)
            ELSE ''
       END AS references_table
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu
  ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
WHERE tc.table_schema = 'public'
  AND tc.constraint_type IN ('PRIMARY KEY', 'FOREIGN KEY', 'UNIQUE')
GROUP BY tc.table_name, tc.constraint_name, tc.constraint_type, tc.table_schema
ORDER BY tc.table_name, tc.constraint_type;
" | awk -F'|' '
{
  gsub(/^ +| +$/, "", $1)
  gsub(/^ +| +$/, "", $2)
  gsub(/^ +| +$/, "", $3)
  gsub(/^ +| +$/, "", $4)
  ref = ($4 != "") ? "→ " $4 : ""
  printf "| `%s` | `%s` | %s | %s |\n", $1, $2, $3, ref
}
'

echo ""
echo "---"
echo ""
echo "## RLS Policies"
echo ""
echo "| Table | Policy | Operation | Using | With Check |"
echo "|-------|--------|-----------|-------|------------|"
run_psql -c "
SELECT tablename, policyname, cmd,
       COALESCE(qual, 'true'),
       COALESCE(with_check, '')
FROM pg_policies
WHERE schemaname = 'public'
ORDER BY tablename, policyname;
" | awk -F'|' '
{
  gsub(/^ +| +$/, "", $1)
  gsub(/^ +| +$/, "", $2)
  gsub(/^ +| +$/, "", $3)
  gsub(/^ +| +$/, "", $4)
  gsub(/^ +| +$/, "", $5)
  printf "| `%s` | %s | %s | `%s` | `%s` |\n", $1, $2, $3, $4, $5
}
'

if [ -n "$VIEW_NAMES" ]; then
  echo ""
  echo "---"
  echo ""
  echo "## Views"
  echo ""
  echo "$VIEW_NAMES" | while IFS= read -r vname; do
    echo "### \`$vname\`"
    echo ""
    echo '```sql'
    run_psql -c "SELECT pg_get_viewdef('public.$vname', true);"
    echo '```'
    echo ""
  done
fi

# User-defined functions (exclude C-language extension functions)
echo ""
echo "---"
echo ""
echo "## Functions"
echo ""
echo "| Name | Returns | Language |"
echo "|------|---------|----------|"
run_psql -c "
SELECT p.proname,
       pg_catalog.pg_get_function_result(p.oid),
       l.lanname
FROM pg_proc p
JOIN pg_namespace n ON p.pronamespace = n.oid
JOIN pg_language l ON p.prolang = l.oid
WHERE n.nspname = 'public'
  AND p.prokind = 'f'
  AND l.lanname IN ('plpgsql', 'sql')
ORDER BY p.proname;
" | awk -F'|' '
{
  gsub(/^ +| +$/, "", $1)
  gsub(/^ +| +$/, "", $2)
  gsub(/^ +| +$/, "", $3)
  printf "| `%s` | %s | %s |\n", $1, $2, $3
}
'

# Non-unique indexes (PK and UNIQUE already covered in Constraints)
echo ""
echo "---"
echo ""
echo "## Indexes"
echo ""
echo "| Table | Index | Definition |"
echo "|-------|-------|------------|"
run_psql -c "
SELECT tablename, indexname, indexdef
FROM pg_indexes
WHERE schemaname = 'public'
  AND indexdef NOT LIKE 'CREATE UNIQUE INDEX%'
  AND indexname !~ '_pkey$'
ORDER BY tablename, indexname;
" | awk -F'|' '
{
  gsub(/^ +| +$/, "", $1)
  gsub(/^ +| +$/, "", $2)
  gsub(/^ +| +$/, "", $3)
  # Strip the "CREATE INDEX ... ON public.X USING btree " prefix for conciseness
  def = $3
  sub(/^CREATE INDEX [^ ]+ ON public\.[^ ]+ USING [^ ]+ /, "", def)
  printf "| `%s` | `%s` | %s |\n", $1, $2, def
}
'

} > "$OUT"

echo "Wrote schema docs to $OUT"
