name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    name: ci/check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: app/package-lock.json

      - run: npm ci

      - run: npm run typecheck

      - run: npm run lint

      - run: npm run test:run

      - run: npm run format:check

  check-bt:
    name: ci/check-bt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/bt

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: packages/bt/package-lock.json

      - run: npm ci

      - run: npm run typecheck

      - run: npm test
